title: Title of your CV site
profile_img: assets/img/profile.webp
icon_img: assets/img/icon.webp

name: "Vikrant Kamble"
job: "Young Professional II (IT)"

phone_number: 808-749-2636
address: New Delhi, India
email: vikrantpkamble@gmail.com
linkedin_username: VikrantPKamble
github_username: VikrantPKamble
instagram_username: VikrantPKamble
twitter_username: VikrantPKamble
facebook_username: fVikrantPKamble
youtube_username: yVikrantPKamble
blog_url: vikrantpkamble.github.io

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
